[theme]
background = "#333333"
primary = "#E5E5E5"
secondary = "#ED764D"
title = "#FFFFFF"
playing = "#FFFFFF"
playing_selected = "#FFFFFF"
playing_bg = "#87A851"
highlight = "#CDCDCD"
highlight_bg = "#87A851"
error = "#C7162B"
error_bg = "#181818"
statusbar = "#000000"
statusbar_progress = "#0E8420"
statusbar_bg = "#0E8420"
cmdline = "#E5E5E5"
cmdline_bg = "#333333"
