[theme]
background = "#FFFFFF"
primary = "#181818"
secondary = "#ED764D"
title = "#000000"
playing = "#FFFFFF"
playing_selected = "#FFFFFF"
playing_bg = "#E95420"
highlight = "#FFFFFF"
highlight_bg = "#E95420"
error = "#C7162B"
error_bg = "#181818"
statusbar = "#000000"
statusbar_progress = "#0E8420"
statusbar_bg = "#0E8420"
cmdline = "#181818"
cmdline_bg = "#FFFFFF"
